// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SangokuKmy.Models.Data;

namespace SangokuKmy.Migrations
{
  [DbContext(typeof(MainContext))]
  partial class MainContextModelSnapshot : ModelSnapshot
  {
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder
        .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
        .HasAnnotation("Relational:MaxIdentifierLength", 64);

      modelBuilder.Entity("SangokuKmy.Models.Data.Entities.AuthenticationData", b =>
        {
          b.Property<uint>("Id")
            .ValueGeneratedOnAdd()
            .HasColumnName("id");

          b.Property<string>("AccessToken")
            .HasColumnName("access_token")
            .HasColumnType("varchar(256)");

          b.Property<uint>("CharacterId")
            .HasColumnName("character_id");

          b.Property<DateTime>("ExpirationTime")
            .HasColumnName("expiration_time");

          b.Property<uint>("Scope")
            .HasColumnName("scope");

          b.HasKey("Id");

          b.ToTable("authentication_data");
        });
#pragma warning restore 612, 618
    }
  }
}
